# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json tsconfig.json .
COPY server.ts types.d.ts .
COPY docs ./docs
COPY test-sdk-import.js .

RUN npm install && npm run build

EXPOSE 3000

CMD ["node", "dist/server.js"]
